### ISSUE TITLE
ModuleNotFoundError: No module named '_init_paths'

### ISSUE THREAD

**Issue by yunsujeon** [aai4r/aai4r-ServiceContextUnderstanding#1]
요소모듈 검증중 이슈사항에 대한 질문입니다.

환경구축및 수행 과정 :
- docker (https://hub.docker.com/r/dereknlp/fasterrcnn) 를 이용했습니다.
- fasterrcnn에서 다른 부분은 수행하지 않고 sh make.sh만 수행했습니다.

////

python my_demo_det_cls.py --image_dir "IMAGE" 실행 시 
Traceback (most recent call last):
  File "my_demo_det_cls.py", line 10, in <module>
    import _init_paths
ModuleNotFoundError: No module named '_init_paths'
와 같은 오류가 발생합니다. 

faster-rcnn.pytorch 에는 _init_paths.py가 존재하는데 이를 이용하면 되는것인지 궁금합니다.

**Comment by yochin** [comment]
그 파일을 사용하셔도 되고, 동일한 파일을 다시 업로드하였습니다.
