### ISSUE TITLE
FoodClassifier에서 senet의 의미

### ISSUE THREAD

**Issue by yunsujeon** [aai4r/aai4r-ServiceContextUnderstanding#2]
my_demo_det_cls.py 의 foodclassifier에서 senet에 대해 질문이 있습니다.

food_classifier = FoodClassifier(net='senet154', dbname='Kfood', eval_crop_type='CenterCrop', ck_file='output/model_best.pth.tar')

와 같이 되어있는데 senet154는 pretrined model인지.. 제공이 되지 않아 질문드립니다.

**Comment by yochin** [comment]
senet154는 아키텍쳐명이며 학습된 파일은 output/model_best.pth.tar입니다.
