### ISSUE TITLE
ModuleNotFoundError: No module named ~

### ISSUE THREAD

**Issue by yunsujeon** [aai4r/aai4r-ServiceContextUnderstanding#3]
계속해서 여러 다른 모듈이 로드되지 않는 상황입니다.

우선 _init_paths 가 faster_rcnn의 것과 같다고 하셔서 로드되지 않는 모듈을 복사하여 datasets 나 models에 복사해가며 실행해보는 중 존재하지 않는 모듈이 있어 발생한 상황입니다. 

`  File "my_demo_det_cls.py", line 28, in <module>
    from roi_data_layer.roidb import combined_roidb
ModuleNotFoundError: No module named 'roi_data_layer'`

의 오류가 있었습니다. 여기서 faster rcnn/lib의 roi_data_layer.roidb를 lib에 복사해주고 실행시켜 보니

  File "my_demo_det_cls.py", line 28, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/root/share/aai4r-ServiceConetxtUnderstanding/lib/roi_data_layer/roidb.py", line 12, in <module>
    from datasets.factory import get_imdb
  File "/root/share/aai4r-ServiceConetxtUnderstanding/lib/datasets/factory.py", line 15, in <module>
    from datasets.pascal_voc_water import pascal_voc_water
ModuleNotFoundError: No module named 'datasets.pascal_voc_water'

와 같이 떴고 이는 factory.py에서 get_imdb를 불러오고자 하는데 pascal_voc_water 이 존재하지 않는 오류였습니다.

factory.py를 보니 로드할 모듈이 많은데 faster-rcnn 의 factory.py는 로드할 모듈이 많지 않아보였습니다.

혹시 local에 가지고 계신 모듈이 존재하는건지..해결방법을 알려주시면 감사하겠습니다

**Comment by yochin** [comment]
README를 수정하였습니다. faster-rcnn.pytorch폴더 내 모든 파일을 aai4r-ServiceContextUnderstanding폴더로 복사 후, 재 실행 부탁드립니다.
