### ISSUE TITLE
environment 구성에 대해서

### ISSUE THREAD

**Issue by yunsujeon** [aai4r/aai4r-ServiceContextUnderstanding#4]
현재 faster-rcnn environment 에 따라
pytorch 0.4.0 (0.4.1 이상X)
cuda 8
cudnn 7.6
torchvision 0.2.1
의 환경에서 진행하고 있습니다.

AttributeError: module 'torch.nn' has no attribute 'ModuleDict' 에러가 발생하는데
찾아보니 torch version을 0.4.1 이상으로 올리라고 합니다.

이외에도
ModuleNotFoundError: No module named 'torchvision.ops' (torchvision의 버전을 올려야되는)
ModuleNotFoundError: No module named 'tqdm' (torchvision 버전문제)
등의 환경구축 문제가 발생합니다.

현재 구성 환경이 어떻게 되는지 알 수 있을까요?

**Comment by yochin** [comment]
죄송합니다. 제가 pytorch 0.4.0으로 처음 작업을 하다가, 1.3.0으로 올리면서 코드를 일부 수정하면서 발생한 문제 같습니다.

pytorch는 1.3.0으로 faster-rcnn부분은 설치 없는 버전으로 Readme를 다시 수정하였습니다.
pytorch 1.3.0, torchvision 0.4.1로 작업하였습니다.

번거롭게 해드려 죄송합니다.

윤우한 드림.


-----Original Message-----

**Comment by yunsujeon** [comment]
감사합니다 다시 해보겠습니다!
