### ISSUE TITLE
Please provide an API for serving food detection.

### ISSUE THREAD

**Issue by zebehn** [aai4r/aai4r-ServiceContextUnderstanding#5]
### Feature Request

I am building a food detection server in a ROS2/REST docker container.

I would like to have an API according to the following specification.

### Output: a JSON string of detections (bbox + class id)

ex) ```[{'x1':100, 'y1':100, 'x2':200, 'y2':200, 'id':124}, {'x1':300, 'y1':100, 'x2':400, 'y2':200, 'id':11}]```

**Comment by zebehn** [comment]
A skeleton code is added. 

Please implement FoodDetector class in the [skeleton code](https://github.com/aai4r/aai4r-ServiceContextUnderstanding/blob/d715d4c711ce7c178596aba956bf54541cc91552/interface/food_detector_interface.py).

**Comment by yochin** [comment]
FoodDetector class를 구현하였습니다.
[ReadMe에 있는 weight파일들](https://drive.google.com/drive/folders/1rT2DYaiywGt8gqdl2YGnd6RLP1rxZV9I)을 다시 다운받고 실행하시면 됩니다.

**Comment by zebehn** [comment]
인식기를 실행하면 초기에 senet 체크포인트를 다운로드하는데 상당히 오래 걸리네요.

미리 모델 파일을 제공하고 해당 모델을 로딩하도록 하면 좋겠습니다.

지금 상태로는 Docker Container를 배포할 때 마다 다운로드를 하게 되어 사용하기 불편해 보입니다.

혹시 해결책이 있으면 알려주세요.

-----Original Message-----

**Comment by yochin** [comment]
하드디스크에서 GPU로 올리는데, 시간이 걸립니다. senet이 900메가 가까이 나가기에 그렇습니다.

현재 구조는 초기화시에 검출 및 인식 모델 관련 정보를 모두 로딩하고 있습니다.
현재는 Handler함수가 선언될 때, 한번 부르도록 되어있습니다.
초기화를 미리하면 로딩하는 속도를 줄일 수 있을 것 같은데, Docker Container상 동작 방식을 몰라 구현 방법은 잘 모르겠습니다.

이 부분이 많이 문제가 되면, 가벼운 network로 백본을 바꾸면 됩니다. (성능은 좀 떨어질 수 있습니다).

윤우한 드림.




-----Original Message-----

**Comment by yochin** [comment]
별다른 이슈가 없기에 닫습니다.
