### ISSUE TITLE
Image Demo 중 오류가 생겨 질문드립니다.

### ISSUE THREAD

**Issue by Bonyeong1998** [aai4r/aai4r-ServiceContextUnderstanding#6]
![스크린샷, 2022-01-05 13-15-57](https://user-images.githubusercontent.com/73810809/148159848-726ecefa-0fce-4d24-90b6-adc4bd75fe1d.png)
20시간전에 최신화 된 파일을 받아 Image Demo를 해보는데 사진처럼 더이상 진행되지 않습니다.
line 319에 pretrained = True로 변경하여 테스트 하면 될까요?

**Comment by yochin** [comment]
어제오늘 코드 최적화 작업을 하던 중에 오류가 있었던 것 같습니다.
조금 전에 수정하였으니, 새로 전체코드를 다운 받아서 해보시고, 안되면 다시 글 남겨주세요.

**Comment by Bonyeong1998** [comment]
전체코드 다운 받고 실행하였는데 안되어서 [my_demo_det_multi.py line 319](https://github.com/aai4r/aai4r-ServiceContextUnderstanding/blob/master/my_demo_det_multi.py)의 pretrained 값을 True로 변경하였더니 진행되나 
![스크린샷, 2022-01-04 16-52-15](https://user-images.githubusercontent.com/73810809/148027789-887cf088-b89b-45e3-99c2-e402ab79a5b4.png)
위와 같은 오류가 발생합니다
현재 README와 동일한 pytorch 1.3.0 pytorchvision 0.4.1로 진행중인데 사용중이신 pytorch와 pytorchvision 버전을 알 수 있을까요?
```
$ conda uninstall pytorch
$ conda install pytorch pytorchvision pytorchaudio cudatoolkit=10.1 -c pytorch
```
현재 위의 명령어로 재설치 중입니다

**Comment by yochin** [comment]
저도 1.3.0, torchvision 0.4.1을 사용중입니다.
위 에러는 pytorch 버전과 CUDA버전이 안맞아서 발생한다고 하네요.
말씀하신 것 처럼 다시 설치하면 될 것 같습니다. 
안되면 다시 알려주세요.
